// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using User_Authapi.Data;

#nullable disable

namespace User_Authapi.Migrations
{
    [DbContext(typeof(UsersDbcontext))]
    [Migration("20250514060717_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("User_Authapi.DTO_s.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RestoredAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedAt = new DateTime(2024, 4, 19, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "wale@gmail.com",
                            IsDeleted = false,
                            Password = "AQAAAAIAAYagAAAAELZsXLwYZc74iPl1YpZq9E31HbU1M8HBIUX1p5rfeM2MbYxq+vJXqXfsBQcOq1bYlw==",
                            UserName = "wale fagbemi"
                        },
                        new
                        {
                            Id = -2,
                            CreatedAt = new DateTime(2024, 4, 19, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "moji@gmail.com",
                            IsDeleted = false,
                            Password = "AQAAAAIAAYagAAAAEM1eECxq3JHBoRxHJdSe+LRfkpRdn0+wxlmAGXxjP6u4bqpN28TmU7DD2chPb6heqA==",
                            UserName = "moji fagbemi"
                        },
                        new
                        {
                            Id = -3,
                            CreatedAt = new DateTime(2024, 4, 19, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "elizabeth@gmail.com",
                            IsDeleted = false,
                            Password = "AQAAAAIAAYagAAAAENcXqWZsR2qRhf1O5H1jdfbwPQkY2u7S93z5WMr9ixgKeB3l0KkJ4Xb3KmUjDLQNDg==",
                            UserName = "elizabeth fagbemi"
                        });
                });

            modelBuilder.Entity("User_Authapi.Entities.RefreshTokens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("User_Authapi.Entities.UserSessions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LoggedInAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LoggedOutAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("User_Authapi.Entities.RefreshTokens", b =>
                {
                    b.HasOne("User_Authapi.DTO_s.Person", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("User_Authapi.Entities.UserSessions", b =>
                {
                    b.HasOne("User_Authapi.DTO_s.Person", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("User_Authapi.DTO_s.Person", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
